use hozan7

create table Student(
STNO SMALLINT PRIMARY KEY NOT NULL,
SNAME NVARCHAR(20) NULL,
DEPT NVARCHAR(4) NULL,
STAGE SMALLINT NULL,
BDATE SMALLDATETIME NULL);

create table Department(
DCODE NVARCHAR(4) PRIMARY KEY NOT NULL,
DNAME NVARCHAR(20));

create table Dependent(
PNO SMALLINT NOT NULL,
DNAME NVARCHAR(20) NULL,
RELATIONSHIP NVARCHAR(8) NULL,
SEX CHAR(1) NULL,
AGE SMALLINT NULL);

create table Section(
SECTION_ID SMALLINT PRIMARY KEY NOT NULL,
COURSE_NUM NVARCHAR(8),
SEMESTER NVARCHAR(6),
[YEAR] CHAR(2),
INSTRUCTOR NVARCHAR(10),
BLDG SMALLINT,
ROOM SMALLINT);

create table Grade_report(
STUDENT_NUMBER SMALLINT NOT NULL,
SECTION_ID SMALLINT NOT NULL,
GRADE CHAR(1)
CONSTRAINT stno_secid PRIMARY KEY (STUDENT_NUMBER,
SECTION_ID));

create table Course(
COURSE_NAME NVARCHAR(20),
COURSE_NUMBER NVARCHAR(8) PRIMARY KEY NOT NULL,
CREDIT_HOURS SMALLINT,
OFFERING_DEPT NVARCHAR(4));

create table Room(
BLDG SMALLINT NOT NULL,
ROOM SMALLINT NOT NULL,
CAPACITY SMALLINT,
OHEAD NVARCHAR(1)
CONSTRAINT bldg_room PRIMARY KEY(BLDG, ROOM));

